# Backtest mode configuration - extends base.yaml
# Override settings for historical data backtesting

framework:
  # Set to backtest mode
  mode: backtest
  
  # Faster step interval for backtest (data-driven, not time-based)
  global_step_interval_minutes: 0  # Disabled in backtest mode
  
  # Faster monitoring for backtest
  service_monitor_interval: 5
  
  # Backtest-specific data fetch configuration
  data_fetch:
    # Historical data configuration
    historical_data_path: data/backtest/
    
    # Backtest time range
    backtest_start_date: "2024-01-01"
    backtest_end_date: "2024-12-31"
    
    # Data granularity for backtest
    data_interval: "1h"  # 1 hour bars
    
    # Backtest data sources
    sources:
      - name: historical_binance
        type: historical
        file_pattern: "{symbol}_{interval}.parquet"
        symbols: ['BTC/USDT', 'ETH/USDT', 'ADA/USDT', 'SOL/USDT']
  
  # Faster analytics for backtest
  analytics:
    analysis_trigger_threshold: 50
    analysis_interval_minutes: 10

# Backtest-specific strategies
strategies:
  backtest_momentum_strategy:
    symbols: ['BTC/USDT', 'ETH/USDT']
    initial_capital: 100000
    position_size: 5000
    risk_threshold: 0.03
    
    # Backtest-specific parameters
    lookback_periods: 24  # 24 hours for 1h data
    momentum_threshold: 0.05
    
    tasks:
      market_analysis:
        interval_seconds: 0  # Analyze every data point
        enabled: true
      order_execution:
        order_type: market
        max_slippage: 0.001  # Stricter slippage for backtest
        timeout_seconds: 10   # Faster timeout

  backtest_mean_reversion_strategy:
    symbols: ['ETH/USDT', 'ADA/USDT']
    initial_capital: 50000
    position_size: 2000
    risk_threshold: 0.02
    
    # Mean reversion parameters
    bollinger_periods: 20
    bollinger_std: 2.0
    rsi_periods: 14
    rsi_overbought: 70
    rsi_oversold: 30
    
    tasks:
      market_analysis:
        interval_seconds: 0
        enabled: true
      order_execution:
        order_type: market
        max_slippage: 0.001
        timeout_seconds: 10

# Backtest logging - more detailed
logging:
  level: DEBUG
  file: logs/backtest.log
  console: true
  
  services:
    scheduler: DEBUG
    data_fetch: INFO
    data_analytics: INFO
    state_management: DEBUG
    strategies: DEBUG
    tasks: INFO